# Generated by Django 2.2.1 on 2019-05-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contents', models.TextField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.City')),
            ],
            options={
                'db_table': 'steptwo_contents',
            },
        ),
        migrations.CreateModel(
            name='StepThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contents', models.TextField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.City')),
            ],
            options={
                'db_table': 'stepthree_contents',
            },
        ),
        migrations.CreateModel(
            name='StepOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contents', models.TextField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.City')),
            ],
            options={
                'db_table': 'stepone_contents',
            },
        ),
    ]
