# Generated by Django 2.2.1 on 2019-06-03 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255, null=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.CarModel')),
            ],
            options={
                'db_table': 'car_types',
            },
        ),
        migrations.CreateModel(
            name='CarTrim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255, null=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.CarModel')),
            ],
            options={
                'db_table': 'car_trims',
            },
        ),
        migrations.CreateModel(
            name='CarDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255, null=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.CarModel')),
            ],
            options={
                'db_table': 'car_designs',
            },
        ),
    ]
