# Generated by Django 2.2.1 on 2019-07-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_cardesign_cartrim_cartype'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_body_sub_type', models.CharField(max_length=255, null=True)),
                ('car_body_type', models.CharField(max_length=255, null=True)),
                ('car_brand', models.CharField(max_length=255, null=True)),
                ('car_model', models.CharField(max_length=255, null=True)),
                ('car_type', models.CharField(max_length=255, null=True)),
                ('car_year', models.CharField(max_length=255, null=True)),
                ('kilometer', models.CharField(max_length=255, null=True)),
                ('user_email', models.CharField(max_length=255, null=True)),
                ('user_message', models.CharField(max_length=255, null=True)),
                ('vehicle_type', models.CharField(max_length=255, null=True)),
                ('user_address', models.CharField(max_length=255, null=True)),
                ('user_firstname', models.CharField(max_length=255, null=True)),
                ('user_lastname', models.CharField(max_length=255, null=True)),
                ('user_phone', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_contact_requests',
            },
        ),
    ]
